### PR TITLE
Added Marathi language, updated Hindi to the match English

### PR DESCRIPTION
**Pull request by anjannair**
Although the Hindi file shows a lot of changes its just Prettier code alignment changes. Same goes for English.

**Waiting for verification from one of the following tagged below as I am doubtful about usage of a few words in the Marathi file.**

### CODE REVIEW

**Comment by anjannair** [comment]
@ShripadJagtap @Phantonym21 please verify the Marathi file that can be found [here](https://github.com/VueTubeApp/VueTube/pull/518/commits/8230d120374f541cde163dda3ee6ef90d75d4e46#diff-70079e47000f7bc532b7747b9b7bfcdd4c4e97104dd05bd24afbe02027e1d83e)

**Comment by Cibapatel** [comment]
It looks correct to me!

**Comment by anjannair** [comment]
@Frontesque can be merged!

**Review by PickleNik — APPROVED** [review]
All commas are in place, good work, thanks 👍🏼

**Pull request merged**
