### PR TITLE
New in-app translations (Developer mode)

### PR DESCRIPTION
**Pull request by gayolGate**
- Implemented Developer Mode fields in Spanish.js and English.js
- Changed Developer.vue to make text appear translated

I almost forgot: CHECK BEFORE MERGING I DONT WANT TO DESTROY VUETUBE

### CODE REVIEW

**Comment by Frontesque** [comment]
The language file loader isnt called on this page. Please view [~/pages/mods/general.vue#L36-L38](https://github.com/VueTubeApp/VueTube/blob/main/NUXT/pages/mods/general.vue#L36-L38) for how to properly import the language files.

**Comment by gayolGate** [comment]
> The language file loader isnt called on this page. Please view [~/pages/mods/general.vue#L35-L38](https://github.com/VueTubeApp/VueTube/blob/main/NUXT/pages/mods/general.vue#L35-L38) for how to properly import the language files.

Ok, I think its now correct, this is what I added:
image

**Comment by Frontesque** [comment]
you dont need to require it as a component

**Comment by gayolGate** [comment]
> you dont need to require it as a component

I removed the component lines, is It fine now?

**Pull request merged**
