### PR TITLE
Update indonesian.js

### PR DESCRIPTION
**Pull request by EatVanced**
Changing 

Custom to Kustom
Log to Catatan (could be optional)

### CODE REVIEW

**Review by anjannair — CHANGES_REQUESTED** [review]
Can you have look at

1.  https://github.com/EatVanced/VueTube/blob/8561fb5050cef9c6ff03f9a03ab428125943d061/NUXT/plugins/languages/indonesian.js#L11
2. https://github.com/EatVanced/VueTube/blob/8561fb5050cef9c6ff03f9a03ab428125943d061/NUXT/plugins/languages/indonesian.js#L6

I think these also can be translated to Indonesian

**Comment by EatVanced** [comment]
the first one could be "Baik", but "OK" is fine
The first one without the s, not translated with stock youtube app

**Comment by anjannair** [comment]
> the first one could be "Baik", but "OK" is fine The first one without the s, not translated with stock youtube app

How about **Oke** for "Okay"? Because the English one mentions "Okay" and according to your translation "OK" looks a bit passive aggressive.

Subscription checks out fine alright

@EatVanced

**Comment by EatVanced** [comment]
Sure, sounds great

**Comment by anjannair** [comment]
> Sure, sounds great

Alright do make that tiny change and I feel it'll be good to go!

**Review by PickleNik — APPROVED** [review]
Thanks 👍🏼

**Pull request merged**
