### PR TITLE
Visual embeds in Readme

### PR DESCRIPTION
**Pull request by gayolGate**
I designed and added some visual embeds in the Readme page. Please check them and add them if you like the result.
Also I added the images into the Resources folder - please move then if they shouldn't be there.

### CODE REVIEW

**Comment by gayolGate** [comment]
2B0B3C9E-9502-42B4-BCAB-8509BB8227F8

**Comment by gayolGate** [comment]
2B0B3C9E-9502-42B4-BCAB-8509BB8227F8

**Comment by 404-Program-not-found** [comment]
can you make the images smaller? it feels too big

**Review by 404-Program-not-found — CHANGES_REQUESTED** [review]
please change the image source to use relative instead of absolute URLs (i.e
/resources/vuetube.png vs https://raw.githubusercontent.com/gayolGate/VueTube/main/resources/vuetube.png)

**Comment by gayolGate** [comment]
> please change the image source to use relative instead of absolute URLs (i.e
> /resources/vuetube.png vs https://raw.githubusercontent.com/gayolGate/VueTube/main/resources/vuetube.png)

I didn’t realized, sorry
All changes done (relative paths and width 500 -> 300)

**Pull request merged**
