### PR TITLE
Readme Banner Changes and ReadMe Cleanup

### PR DESCRIPTION
**Pull request by afnzmn**

### CODE REVIEW

**Comment by 404-Program-not-found** [comment]
hmm, I'm not so sure about that banner. @Frontesque what do you think?

**Comment by afnzmn** [comment]
> hmm, I'm not so sure about that banner. @Frontesque what do you think?

Hmm then I can change the existing banner's text to #00dcc8 so that it is visible in both light and dark mode if you want.

**Comment by 404-Program-not-found** [comment]
No, it's not the color per se. The overall design doesn't seem to fit a big banner imo

**Comment by afnzmn** [comment]
> No, it's not the color per se. The overall design doesn't seem to fit a big banner imo

Sorry I meant change the banner we have already on the readme to #00dcc8

**Comment by 404-Program-not-found** [comment]
Personally, I don't think a change in the banner is really needed. However, it should be noted that GH now supports a new feature, that being dark and light mode images
```md
![Fancy logo](./dark.png#gh-dark-mode-only)
![Fancy logo](./light.png#gh-light-mode-only)
```

**Comment by afnzmn** [comment]
Oh, that's news to me. I'll do that then in a different PR later.

**Pull request closed without merging**
